### ISSUE TITLE
Inserire l'apposito header User-agent nelle richieste verso le API

### ISSUE THREAD

**Issue by astagi** [mastro993/verificaC19-flutter#14]
Inserire all'interno delle richieste verso le API l'apposito header User-Agent nella forma 

```
User-Agent: <sdk>-<sdk-technology>/<sdk-version>
```

È possibile omettere `-<sdk-technology>` se la tecnologia è già specificata nel nome (ad esempio verificac19-sdk-php).

Ad esempio nel caso `verificac19-sdk` per Node.js lo User-Agent sarà

```
User-Agent: verificac19-sdk-node/0.9.3
```

**Comment by mastro993** [comment]
Aggiunto nella versione 1.4.3
