### ISSUE TITLE
Aggiornamento core per allineamento a release DGC-SDK Android/Kotlin 1.1.11

### ISSUE THREAD

**Issue by astagi** [mastro993/verificaC19-flutter#24]
Buonasera,

si prega di procedere all'aggiornamento del core di questo SDK per allineamento a release DGC-SDK Android/Kotlin 1.1.11.

- Rimozione delle modalità di verifica RSA (booster) e Rafforzata (2G)

- Aggiornamento del flusso di validazione con solo i controlli previsti per la modalità di verifica Base (3G)

Maggiori dettagli: https://github.com/ministero-salute/it-dgc-documentation/pull/29

cc @fede-mas @mastro993

**Comment by mastro993** [comment]
Aggiornato! https://github.com/mastro993/verificaC19-flutter/pull/25/
