### ISSUE TITLE
Error while creating CertificateValidator

### ISSUE THREAD

**Issue by patricknicolosi** [mastro993/verificaC19-flutter#5]
Since version 1.3.0 the validation has stopped working. 

![image](https://user-images.githubusercontent.com/23001470/153745722-aa80f544-0231-4f21-b5e7-eaaa1222ee8a.png)

**Comment by mastro993** [comment]
Hi @patricknicolosi, the problem should be resolver in the 1.3.2 release. 
CertificateValidator dependency tree was not correctly built. 

https://github.com/mastro993/verificaC19-flutter/commit/de1231eb214c55b3ee91cc0b974fcbaa58c0bc0e
