### ISSUE TITLE
Rimuovere la modalità scuola

### ISSUE THREAD

**Issue by astagi** [mastro993/verificaC19-flutter#7]
Rimuovere la modalità scuola secondo il [DECRETO-LEGGE 4 febbraio 2022, n. 5](https://www.gazzettaufficiale.it/eli/id/2022/02/04/22G00014/sg)

```
La condizione sanitaria che consente la didattica in presenza di
cui al comma 1, lettera b), numero 2, primo periodo,  e  lettera  c),
numero 2), primo periodo, puo' essere controllata  dalle  istituzioni
scolastiche mediante l'applicazione  mobile  per  la  verifica  delle
certificazioni verdi COVID-19 di cui al decreto  del  Presidente  del
Consiglio dei ministri adottato ai sensi dell'articolo 9,  comma  10,
del  decreto-legge  22  aprile   2021,   n.   52,   convertito,   con
modificazioni, dalla legge 17  giugno  2021,  n.  87.  L'applicazione
mobile  di  cui  al  primo  periodo  e'  tecnicamente   adeguata   al
conseguimento delle  finalita'  del  presente  comma  e  puo'  essere
impiegata anche nelle more dell'aggiornamento del decreto di  cui  al
primo periodo. 
```

**Comment by patricknicolosi** [comment]
> Rimuovere la modalità secondo il [DECRETO-LEGGE 4 febbraio 2022, n. 5](https://www.gazzettaufficiale.it/eli/id/2022/02/04/22G00014/sg)
> 
> ```
> La condizione sanitaria che consente la didattica in presenza di
> cui al comma 1, lettera b), numero 2, primo periodo,  e  lettera  c),
> numero 2), primo periodo, puo' essere controllata  dalle  istituzioni
> scolastiche mediante l'applicazione  mobile  per  la  verifica  delle
> certificazioni verdi COVID-19 di cui al decreto  del  Presidente  del
> Consiglio dei ministri adottato ai sensi dell'articolo 9,  comma  10,
> del  decreto-legge  22  aprile   2021,   n.   52,   convertito,   con
> modificazioni, dalla legge 17  giugno  2021,  n.  87.  L'applicazione
> mobile  di  cui  al  primo  periodo  e'  tecnicamente   adeguata   al
> conseguimento delle  finalita'  del  presente  comma  e  puo'  essere
> impiegata anche nelle more dell'aggiornamento del decreto di  cui  al
> primo periodo. 
> ```

Ma la modalità per studenti non è presente pure in VerificaC19 ?

**Comment by astagi** [comment]
@patricknicolosi per legge deve essere eseguita solo con l'app ufficiale, quindi non inclusa nei vari SDK.

**Comment by mastro993** [comment]
Ciao @astagi, ho rimosso la modalità scuola. La libreria ora è allineata al DL del 4 Febbraio 2022, n5.

f7aee117745f1af53d3aef5380d3e3e2e77da89a
